# Generated by Django 2.2.10 on 2021-09-20 13:48

from django.db import migrations, models
import django.db.models.deletion
import test_task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('start_at', models.DateTimeField(default=test_task.models.seconds_ago)),
                ('expire_at', models.DateTimeField(default=test_task.models.duration_week)),
                ('description', models.CharField(default="I'm a Poll", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default="What's up?", max_length=255)),
                ('answers', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SA', 'Single answer'), ('MA', 'Multiple answers'), ('TA', 'Text answer')], default='SA', max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test_task.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=32)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='test_task.PollQuestion')),
            ],
            options={
                'unique_together': {('user_id', 'question')},
            },
        ),
    ]
